config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root to: 'users#profile', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end


  get 'users/:id/profile' => 'users#profile', as: 'user_profile'
  get 'users/students' => 'users#students', as: 'students'
  get 'users/:id/show' => 'users#show', as: 'show_user'


  resources :users,
            :contact_lists,
            :sms_deliveries,
            :sms_service_accounts,
            :senders,
            :course_elements,
            :courses,
            :groups,
						:periods

  resources :custom_lists do
    collection {post :import}
  end


  post 'sms_deliveries/:id/send' => 'sms_deliveries#send_message', as: 'sms_send_message'
  get 'select_objects/select_group/:id' => 'select_objects#select_group', as: 'select_groups'
  get 'select_objects/select_students/:id' => 'select_objects#select_students', as: 'select_students'
  get 'sms_deliveries/new_from_contact_list/:id' => 'sms_deliveries#new_from_contact_list', as: 'sms_new_from_contact_list'
  get 'sms_deliveries/resend_message/:id' => 'sms_deliveries#resend_message', as: 'sms_resend'
	get '/calendar' => 'periods#calendar', as: 'calendar'

end

app/models/sms_delivery.rb
class SmsDelivery < ActiveRecord::Base
  belongs_to :contact_list
  belongs_to :sender

  before_validation :fill_title

  validates :title, presence: true, length: { maximum: 70 }
  validates :content, presence: true, length: { maximum: 800 }
  validates :contact_list, presence: true
  validates :sender, presence: true

  def send_message
    url = '/api/message'
    @response = set_url(url, build_message)
    update_attribute(:status, true)
  end

  def build_message
    Nokogiri::XML::Builder.new do |xml|
      xml.message {
        xml.login(sender.sms_service_account.login)
        xml.pwd(sender.sms_service_account.password)
        xml.id(id.to_s + 'importecsdm')
        xml.sender(sender.name)
        xml.text_ content
        xml.phones {

          if contact_list.custom_lists.any?
            contact_list.custom_lists.each do |phone|
              xml.phone(phone.phone)
            end
          else
            contact_list.users.each do |student|
              xml.phone(student.contact.phone)
            end
          end

        }
      }
    end
  end

  def build_report
    Nokogiri::XML::Builder.new do |xml|
      xml.dr {
        xml.login('aisma')
        xml.pwd('kiminitodoke')
        xml.id(id.to_s + 'Mesp1502')
      }
    end
  end

  def parse_report(xml)
    xml_doc = Nokogiri::XML(xml.body)
    xml_doc.remove_namespaces!
    doc = xml_doc.xpath('//phone')
    hash = {}
    doc.each do |phone|
      hash[phone.xpath('number').text] = phone.xpath('report').text
    end
    hash
  end

  private

  def set_url (url, message)
    http = Net::HTTP.new('smspro.nikita.kg')
    http.post(url, message.to_xml)
  end

  def fill_title
    if self.title.blank?
      self.title = self.content[0, 69]
    end
  end
end

app/controllers/sms_deliveries_controller.rb
class SmsDeliveriesController < ApplicationController

  add_breadcrumb 'Рассылки', :sms_deliveries_url

  def index
    @sms_deliveries = SmsDelivery.order(created_at: :desc).paginate(page: params[:page], per_page: 8)
  end

  def show
    @sms_delivery = SmsDelivery.find(params[:id])
    add_breadcrumb @sms_delivery.title, :sms_delivery_url
  end

  def resend_message
    @sms_delivery = SmsDelivery.find(params[:id])
    @sms_delivery = SmsDelivery.new(@sms_delivery.attributes)
    render :new
  end

  def new
    @sms_delivery = SmsDelivery.new
    add_breadcrumb 'Новая рассылка', :new_sms_delivery_url
  end

  def new_from_contact_list
    @sms_delivery = SmsDelivery.new
    @contact_list = ContactList.find(params[:id])
    add_breadcrumb 'Новая рассылка'
  end

  def create
    @sms_delivery = SmsDelivery.new(sms_delivery_params)
    if @sms_delivery.save
      @sms_delivery.update_attribute(:delivery_time, Time.now + 3.minutes)
      flash[:success] = 'СМС рассылка будет отправлена через 3 минуты'
      redirect_to sms_deliveries_url
    else
      flash[:danger] = 'Вы ввели некорректные данные, проверьте и попробуйте снова'
      render 'new'
    end
  end

  def edit
    @sms_delivery = SmsDelivery.find(params[:id])
    add_breadcrumb 'Редактирование рассылки - ' + @sms_delivery.title
  end

  def update
    @sms_delivery = SmsDelivery.find(params[:id])
    if @sms_delivery.update(sms_delivery_params)
      @sms_delivery.updated_at + 3.minutes
      redirect_to sms_deliveries_url
      flash[:success] = 'Сообщение успешно отредактировано'
    else
      flash[:danger] = 'Вы ввели некорректные данные, проверьте и попробуйте снова'
      render 'edit'
    end
  end

  def destroy
    @sms_delivery = SmsDelivery.find(params[:id])
    @sms_delivery.destroy
    flash[:success] = 'Сообщение успешно удалено'
    redirect_to sms_deliveries_url
  end

  def send_message
    @sms = SmsDelivery.find(params[:id])
    @sms.send_message
    redirect_to sms_deliveries_url
    flash[:success] = 'Сообщение Отправлено'
  end

  private

  def sms_delivery_params
    params.require(:sms_delivery).permit(:title, :content, :contact_list_id, :sender_id)
  end

end

app/helpers/sms_deliveries_helper.rb
module SmsDeliveriesHelper
end

app/views/sms_deliveries/_form.html.erb
<%= render 'sidebar_sms_deliveries' %>

<%= form_for @sms_delivery, html: {class: 'form-horizontal'} do |f| %>

    <div class="form-group col-sm-12">
      <%= f.label :content, value: 'Текст*', class: 'col-sm-3 control-label' %>
      <div class="col-sm-6">
        <span>количество символов: </span><span id="char-num"></span>
        <span>количество сообщений: </span><span id="sms-count"></span>
        <%= f.text_area :content, rows: 10, class: 'form-control', id: 'text-field' %>
        <%= render 'shared/field_errors', object: @sms_delivery, field_name: :content %>
      </div>
    </div>

    <div class="form-group col-sm-12">
      <%= f.label :senders, value: 'Отправитель*', class: 'col-sm-3 control-label' %>

      <div class="col-sm-6">
        <%= f.collection_select :sender_id, Sender.all.order(created_at: :desc), :id, :name, {}, class: 'form-control'  %>
      </div>
      <%= render 'shared/field_errors', object: @sms_delivery, field_name: :sender %>
    </div>

		<div class="form-group col-sm-12">
			<%= f.label :contact_list, value: 'Лист получателей*', class: 'col-sm-3 control-label'  %>
			<div class="col-sm-6">
				<%= f.collection_select :contact_list_id, ContactList.all.where(temp: false).order(created_at: :desc), :id, :title, {}, class: 'form-control'  %>
			</div>
			<%= render 'shared/field_errors', object: @sms_delivery, field_name: :contact_list %>
		</div>

		<div class="form-group col-sm-12">
			<div class="col-sm-6 col-sm-offset-3">
				<div class="dropzone" id="my-awesome-dropzone" data-url="<%= import_custom_lists_path %>">
				</div>
			</div>
		</div>

    <div class="form-group col-sm-12">
      <%= f.label :title, value: 'Название*', class: 'col-sm-3 control-label' %>
      <div class="col-sm-6">
        <%= f.text_field :title, autofocus: true, class: 'form-control' %>
        <%= render 'shared/field_errors', object: @sms_delivery, field_name: :title %>
      </div>
    </div>

    <div class="form-group col-sm-12">
      <div class="col-sm-offset-3 col-sm-6">
        <%= f.submit 'Сохранить', class: 'btn btn-default' %>
      </div>
    </div>
<% end %>

app/views/sms_deliveries/_sidebar_sms_deliveries.html.erb
<ul class="nav navbar-nav side-nav">
	<div class="my-avatar">
		<%= link_to image_tag(current_user.photo.url(:thumb), class: 'img-circle'), authenticated_root_path %>
	</div>

	<ul class="nav nav-stacked">
		<li><%= link_to '<i class="fa fa-envelope-o fa-lg"></i> SMS Рассылка'.html_safe, sms_deliveries_path %></li>
		<li><%= link_to '<i class="fa fa-file-text-o fa-lg"></i> Получатели'.html_safe, contact_lists_path %></li>
		<li><%= link_to '<i class="fa fa-user-plus fa-lg"></i> Учетные записи'.html_safe, sms_service_accounts_path %></li>
	</ul>
</ul>

app/views/sms_deliveries/edit.html.erb
%= render 'form' %>

app/views/sms_deliveries/index.html.erb
<%= render 'sidebar_sms_deliveries' %>

<p><%= link_to 'Новая рассылка', new_sms_delivery_path, class: 'btn btn-default margin-bottom' %></p>
  <table class="table table-striped table-hover col-sm-12">
    <tr>
      <th class="col-sm-3">Название рассылки</th>
      <th class="col-sm-2">Лист получателей</th>
      <th class="col-sm-2">Отправитель</th>
      <th class="col-sm-2">Текст смс</th>
      <th class="col-sm-3">Действия</th>
    </tr>
    <div class="row">
    </div>
    <% @sms_deliveries.each do |sms| %>
        <tr>
          <td><%= link_to sms.title, sms_delivery_url(sms) %></td>
          <td><%= sms.contact_list.title %></td>
          <td><%= sms.sender.name %></td>
          <td><%= truncate(sms.content, length: 70) %></td>
          <td>
            <%= form_for sms, url: sms_send_message_path(sms), method: :post do |f| %>
                <% unless sms.status %>
                    <%= f.submit 'Отправить', class: 'btn btn-success btn-xs' %>
                    <%= link_to 'Редактировать', edit_sms_delivery_path(sms), class: 'btn btn-primary btn-xs' %>
                <% end %>
                <%= link_to 'Удалить', sms_delivery_path(sms), method: :delete,
                            data: {confirm: 'Вы действительно хотите удалить эту рассылку?'}, class: 'btn btn-danger btn-xs' %>
            <% end %>
            <%= link_to 'Переотправить', sms_resend_path(sms), class: 'btn btn-primary btn-xs' %>
          </td>
        </tr>
    <% end %>
  </table>
  <div class="row">
    <div class="col-sm-12">
      <%= will_paginate @sms_deliveries %>
    </div>
  </div>

app/views/sms_deliveries/new.html.erb
<%= render 'form' %>

app/views/sms_deliveries/new_from_contact_list.html.erb
<%= form_for @sms_delivery, html: {class: 'form-horizontal'} do |f| %>

    <div class="form-group col-sm-12">
      <%= f.label :content, value: 'Текст*', class: 'col-sm-3 control-label' %>
      <div class="col-sm-6">
        <span>Количество символов: </span><span id="char-num"></span>
        <span>Количество сообщений: </span><span id="sms-count"></span>
        <%= f.text_area :content, rows: 10, class: 'form-control', id: 'text-field' %>
        <%= render 'shared/field_errors', object: @sms_delivery, field_name: :content %>
      </div>
    </div>

    <div class="form-group col-sm-12">
      <%= f.label :senders, value: 'Отправитель*', class: 'col-sm-3 control-label' %>

      <div class="col-sm-6">
        <%= f.collection_select :sender_id, Sender.all.order(created_at: :desc), :id, :name, {}, class: 'form-control' %>
      </div>
      <%= render 'shared/field_errors', object: @sms_delivery, field_name: :sender %>
    </div>

    <div class="form-group col-sm-12">
      <%= f.label :contact_list, value: 'Лист получателей*', class: 'col-sm-3 control-label' %>
      <div class="col-sm-6">
        <%= f.collection_select :contact_list_id, ContactList.all, :id, :title, {:selected => @contact_list.id}, class: 'form-control',
                                :prompt => true, :selected => @contact_list.id  %>
      </div>
      <%= render 'shared/field_errors', object: @sms_delivery, field_name: :contact_list %>
    </div>

    <div class="form-group col-sm-12">
      <%= f.label :title, value: 'Название*', class: 'col-sm-3 control-label' %>
      <div class="col-sm-6">
        <%= f.text_field :title, class: 'form-control' %>
        <%= render 'shared/field_errors', object: @sms_delivery, field_name: :title %>
      </div>
    </div>

    <div class="form-group col-sm-12">
      <div class="col-sm-offset-3 col-sm-6">
        <%= f.submit 'Сохранить', class: 'btn btn-primary' %>
      </div>
    </div>

<% end %>

app/views/sms_deliveries/show.html.erb
<%= render 'sidebar_sms_deliveries' %>
<div class="col-sm-6">
  <div class="panel panel-default">
    <div class="panel-body">
      <table class="table">
        <tr>
          <td>Название</td>
          <td><%= @sms_delivery.title %></td>
        </tr>
        <tr>
          <td>Отправитель</td>
          <td><%= @sms_delivery.sender.name %></td>
        </tr>
        <tr>
          <td>Лист получателей</td>
          <td><%= @sms_delivery.contact_list.title %></td>
        </tr>
        <tr>
          <td>Текст смс</td>
          <td><%= @sms_delivery.content %></td>
        </tr>
        <tr>
          <td></td>
          <td>
            <%= form_for @sms_delivery, url: sms_send_message_path, method: :post do |f| %>
              <%= f.submit 'Отправить', class: 'btn btn-default btn-xs' %>
              <%= link_to 'Редактировать'.html_safe, edit_sms_delivery_path(@sms_delivery), class: 'btn btn-default btn-xs' %>
              <%= link_to 'Удалить'.html_safe, sms_delivery_path(@sms_delivery), method: :delete, class: 'btn btn-danger btn-xs',
                            data: {confirm: 'Вы действительно хотите удалить эту рассылку?'} %>
            <% end %>
          </td>
        </tr>
      </table>
    </div>
  </div>
</div>