config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root to: 'users#profile', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end


  get 'users/:id/profile' => 'users#profile', as: 'user_profile'
  get 'users/students' => 'users#students', as: 'students'
  get 'users/:id/show' => 'users#show', as: 'show_user'


  resources :users,
            :contact_lists,
            :sms_deliveries,
            :sms_service_accounts,
            :senders,
            :course_elements,
            :courses,
            :groups,
						:periods

  resources :custom_lists do
    collection {post :import}
  end


  post 'sms_deliveries/:id/send' => 'sms_deliveries#send_message', as: 'sms_send_message'
  get 'select_objects/select_group/:id' => 'select_objects#select_group', as: 'select_groups'
  get 'select_objects/select_students/:id' => 'select_objects#select_students', as: 'select_students'
  get 'sms_deliveries/new_from_contact_list/:id' => 'sms_deliveries#new_from_contact_list', as: 'sms_new_from_contact_list'
  get 'sms_deliveries/resend_message/:id' => 'sms_deliveries#resend_message', as: 'sms_resend'
	get '/calendar' => 'periods#calendar', as: 'calendar'

end

app/models/contact_list.rb
class ContactList < ActiveRecord::Base
  has_many :recipient_depositories
  has_many :users, through: :recipient_depositories
  has_many :sms_deliveries, dependent: :destroy
  has_many :custom_lists, dependent: :destroy

  validates :title, presence: true, uniqueness: true, length: { maximum: 50 }
  # validates :users, presence: true
end

app/controllers/contact_lists_controller.rb
class ContactListsController < ApplicationController

  add_breadcrumb 'Листы получателей', :contact_lists_url

  def index
    @contact_lists = ContactList.all
  end

  def show
    @contact_list = ContactList.find(params[:id])
    add_breadcrumb @contact_list.title, :contact_list_url
  end

  def new
    @contact_list = ContactList.new
    add_breadcrumb 'Новый лист получателей', :new_contact_list_url
  end

  def create
    @contact_list = ContactList.new(contact_list_params)
    if @contact_list.save
      redirect_to contact_lists_url
      flash[:success] = 'Список получателей успешно создан'
    else
      flash[:danger] = 'Вы ввели некорректные данные, проверьте и попробуйте снова'
      render 'new'
    end
  end

  def edit
    @contact_list = ContactList.find(params[:id])
    add_breadcrumb 'Редактирование листа получателей - ' + @contact_list.title
  end

  def update
    @contact_list = ContactList.find(params[:id])

    if @contact_list.update(contact_list_params)
      flash[:success] = 'Список получателей успешно обновлен'
      redirect_to contact_lists_url
    else
      flash[:danger] = 'Вы ввели некорректные данные, проверьте и попробуйте снова'
      render 'edit'
    end
  end

  def destroy
    @contact_list = ContactList.find(params[:id])
    @contact_list.destroy
    flash[:success] = 'Список получателей удален'

    redirect_to contact_lists_url
  end

  private

  def contact_list_params
    params.require(:contact_list).permit(:title, user_ids: [])
  end
end

app/helpers/contact_lists_helper.rb
module ContactListsHelper
end

app/views/contact_lists/_form.html.erb
<%= render 'sms_deliveries/sidebar_sms_deliveries' %>

<%= form_for @contact_list, html: {class: 'form-horizontal'} do |f| %>

    <div class="form-group col-sm-12">
      <%= f.label 'Название*', class: 'col-sm-3 control-label' %>
      <div class="col-sm-6">
        <%= f.text_field :title, autofocus: true, class: 'form-control' %>
        <%= render 'shared/field_errors', object: @contact_list, field_name: :title %>
      </div>
    </div>

	<div class="form-group col-sm-12">
      <%= f.label 'Контакты*', class: 'col-sm-3 control-label' %>
      <div class="col-sm-6">
	    <%= f.collection_check_boxes(:user_ids, User.all, :id, :name) do |student| %>
    	  <ul class="checkbox">
	        <li>
		      <%= student.check_box %>
			  <%= student.label %><br/>
		    </li>
		  </ul>
	    <% end %>
	  </div>
    </div>

    <!--<div class="form-group col-sm-12">-->
      <!--<%= f.label 'Курс', class: 'col-sm-2 control-label' %>-->
      <!--<div class="col-sm-8">-->
        <!--<%= f.collection_select(:users, Course.all, :id, :name, {:include_blank => "Выберите курс"}, {:id=>'select-course-id'}) %>-->
      <!--</div>-->
    <!--</div>-->

    <!--<div class="form-group col-sm-12">-->
      <!--<%= f.label 'Группа', class: 'col-sm-2 control-label' %>-->
      <!--<div class="col-sm-8">-->
        <!--<%= f.collection_select(:users, [], :id, :name,  {:include_blank => "Выберите группу"}, {:id=>'select-group-id'}) %>-->
      <!--</div>-->
    <!--</div>-->

    <!--<div class="form-group col-sm-12">-->
      <!--<%= f.label 'Контакты', class: 'col-sm-2 control-label' %>-->
      <!--<div class="col-sm-6">-->
        <!--<ul class="checkbox" id="student-list">-->
          <!--<li>Нет данных для отображения</li>-->
        <!--</ul>-->
        <!--<%= render 'shared/field_errors', object: @contact_list, field_name: :students %>-->
      <!--</div>-->
    <!--</div>-->

    <div class="form-group col-sm-12">
      <div class="col-sm-offset-3 col-sm-6">
        <%= f.submit 'Сохранить', class: 'btn btn-default' %>
      </div>
    </div>
<% end %>

app/views/contact_lists/edit.html.erb
<%= render 'form' %>

app/views/contact_lists/index.html.erb
<%= render 'sms_deliveries/sidebar_sms_deliveries' %>

<p><%= link_to 'Новый лист', new_contact_list_path, class: 'btn btn-default margin-bottom' %></p>

<table class="table table-striped table-hover col-sm-12">
  <tr>
    <th class="col-sm-6">Название</th>
    <th class="col-sm-6">Действия</th>
  </tr>
  <% @contact_lists.each do |list| %>
      <tr>
        <td><%= link_to list.title, contact_list_path(list) %></td>
        <td>
          <%= link_to '<i class="fa fa-envelope-o fa-lg"></i>'.html_safe, sms_new_from_contact_list_path(list), class: 'btn btn-default btn-xs' %>
          <%= link_to '<i class="fa fa-pencil-square-o fa-lg"></i>'.html_safe, edit_contact_list_path(list), class: 'btn btn-default btn-xs' %>
          <%= link_to '<i class="fa fa-remove fa-lg"></i>'.html_safe, contact_list_path(list), method: :delete,
                      data: {confirm: 'Вы действительно хотите удалить этот лист получателей?'}, class: 'btn btn-danger btn-xs'  %>
        </td>
      </tr>
  <% end %>
</table>

app/views/contact_lists/new.html.erb
<%= render 'form' %>

app/views/contact_lists/show.html.erb
<%= render 'sms_deliveries/sidebar_sms_deliveries' %>

<div class="col-sm-6">
  <div class="panel panel-default">
    <div class="panel-body">
      <table class="table">
        <tr>
          <% @contact_list.users.each do |student| %>
          <tr>
            <td class="col-sm-3"><%= student.name %></td>
            <td class="col-sm-2">
              <%= student.contact.phone %>
            </td>
            <td class="col-sm-1">
              <%= link_to '<i class="fa fa-remove"></i>'.html_safe, user_path(student), method: :delete,
                          data: {confirm: 'Вы действительно хотите удалить данные студента?'}, class: 'btn btn-danger btn-xs' %>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>