config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root to: 'users#profile', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end


  get 'users/:id/profile' => 'users#profile', as: 'user_profile'
  get 'users/students' => 'users#students', as: 'students'
  get 'users/:id/show' => 'users#show', as: 'show_user'


  resources :users,
            :contact_lists,
            :sms_deliveries,
            :sms_service_accounts,
            :senders,
            :course_elements,
            :courses,
            :groups,
						:periods

  resources :custom_lists do
    collection {post :import}
  end


  post 'sms_deliveries/:id/send' => 'sms_deliveries#send_message', as: 'sms_send_message'
  get 'select_objects/select_group/:id' => 'select_objects#select_group', as: 'select_groups'
  get 'select_objects/select_students/:id' => 'select_objects#select_students', as: 'select_students'
  get 'sms_deliveries/new_from_contact_list/:id' => 'sms_deliveries#new_from_contact_list', as: 'sms_new_from_contact_list'
  get 'sms_deliveries/resend_message/:id' => 'sms_deliveries#resend_message', as: 'sms_resend'
	get '/calendar' => 'periods#calendar', as: 'calendar'

end

app/models/group.rb
class Group < ActiveRecord::Base
  validates :name, presence: true, length: {maximum:20}

  belongs_to :course
  has_many :group_memberships
  has_many :users, through: :group_memberships
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = Group.order(created_at: :desc).paginate(page: params[:page], per_page: 8)
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      flash[:success] = 'Группа успешно создана'
      redirect_to groups_url
    else
      flash[:danger] = 'Вы ввели некорректные данные, проверьте и попробуйте снова'
      render 'new'
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to groups_url
      flash[:success] = 'Группа успешно отредактирована'
    else
      flash[:danger] = 'Вы ввели некорректные данные, проверьте и попробуйте снова'
      render 'edit'
    end
  end

  def show
    @group = Group.find(params[:id])
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    flash[:success] = 'Группа успешно удалена'
    redirect_to groups_url
  end

  private
  def group_params
    params.require(:group).permit(:name, :course_id)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= render 'users/sidebar_users' %>
<%= form_for @group, html: {class: 'from-horizontal'} do |f| %>

    <div class="form-group col-sm-12">
      <%= f.label :name, value: 'Имя*', class: 'col-sm-3 control-label' %>
      <div class="col-sm-6">
        <%= f.text_field :name, class: 'form-control' %>
        <%= render 'shared/field_errors', object: @group, field_name: :name %>
      </div>
    </div>

    <div class="form-group col-sm-12">
      <%= f.label :login, value: 'Курс*', class: 'col-sm-3 control-label' %>
      <div class="col-sm-6">
        <%= f.collection_select :course_id, Course.all.order(created_at: :desc), :id, :name, {}, class: 'form-control' %>
      </div>
    </div>


    <div class="form-group col-sm-12">
      <div class="col-sm-offset-3 col-sm-6">
        <%= f.submit 'Сохранить', class: 'btn btn-default' %>
      </div>
    </div>

<% end %>

app/views/groups/edit.html.erb
<%= render 'form' %>

app/views/groups/index.html.erb
<%= render 'users/sidebar_users' %>

<p><%= link_to 'Создать группу', new_group_path, class: 'btn btn-default margin-bottom' %></p>

<table class="table table-striped table-hover col-sm-12">
  <tr>
    <th>Пользователь</th>
    <th>Действия</th>
  </tr>

  <% @groups.each do |group| %>
      <tr>
        <td><%= link_to group.name, group_path(group) %></td>
        <td>
          <%= link_to '<i class="fa fa-pencil-square-o fa-lg"></i>'.html_safe, edit_group_path(group), class: 'btn btn-default btn-xs' %>
          <%= link_to '<i class="fa fa-remove fa-lg"></i>'.html_safe, group_path(group), method: :delete,
                      data: {confirm: 'Вы действительно хотите удалить данную группу?'}, class: 'btn btn-danger btn-xs' %>
        </td>
      </tr>
  <% end %>
</table>
<div class="row">
  <div class="col-sm-12">
    <%= will_paginate @groups %>
  </div>
</div>

app/views/groups/new.html.erb
<%= render 'form' %>

app/views/groups/show.html.erb
<%= render 'users/sidebar_users' %>

<h1>Show one Group</h1>
<%= @group.name %>
<br>
<br>
<%= @group.course.name %>