config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root to: 'users#profile', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end


  get 'users/:id/profile' => 'users#profile', as: 'user_profile'
  get 'users/students' => 'users#students', as: 'students'
  get 'users/:id/show' => 'users#show', as: 'show_user'


  resources :users,
            :contact_lists,
            :sms_deliveries,
            :sms_service_accounts,
            :senders,
            :course_elements,
            :courses,
            :groups,
						:periods

  resources :custom_lists do
    collection {post :import}
  end


  post 'sms_deliveries/:id/send' => 'sms_deliveries#send_message', as: 'sms_send_message'
  get 'select_objects/select_group/:id' => 'select_objects#select_group', as: 'select_groups'
  get 'select_objects/select_students/:id' => 'select_objects#select_students', as: 'select_students'
  get 'sms_deliveries/new_from_contact_list/:id' => 'sms_deliveries#new_from_contact_list', as: 'sms_new_from_contact_list'
  get 'sms_deliveries/resend_message/:id' => 'sms_deliveries#resend_message', as: 'sms_resend'
	get '/calendar' => 'periods#calendar', as: 'calendar'

end

app/models/user.rb
class User < ActiveRecord::Base
  rolify

  # Include default devise modules. Others available are:
  # :registerable, :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable

  has_many :group_memberships
  has_many :groups, through: :group_memberships

  has_many :attendances
  has_many :periods, through: :attendances

  has_many :recipient_depositories
  has_many :contact_lists, through: :recipient_depositories

  has_one :contact, dependent: :destroy
  accepts_nested_attributes_for :contact

  validates :name, :surname, :passport_data, presence: true
  validates :email, format: { with: /@gmail\.com\z/ }

  has_attached_file :photo,
                    styles: { medium: '300x300>', thumb: '150x150>'},
                    default_url:  '/images/:style/no_avatar.png'
  validates_attachment_content_type :photo,
                                    content_type: ['image/jpeg', 'image/jpg', 'image/gif', 'image/png']

  has_attached_file :passport_scan_copy,
                    styles: { large: '600x600>', medium: '300x300>', thumb: '150x150>'}
  validates_attachment_content_type :passport_scan_copy,
                                    content_type: ['image/jpeg', 'image/jpg', 'image/gif', 'image/png']

  def password_required?
    new_record? ? false : super
  end

  after_initialize do
    self.contact ||= self.build_contact()
  end

  def full_name
    "#{surname} #{name}"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #load_and_authorize_resource

  before_action :authenticate_user!

  def profile
    @user = current_user
    add_breadcrumb 'Мой профиль', :authenticated_root_url
  end

  def show
    @user = User.find(params[:id])
    add_breadcrumb 'Пользователи', :users_url
    add_breadcrumb @user.full_name, :user_url
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 10)
    add_breadcrumb 'Пользователи', :users_url
  end

  def students
    student = Role.find_by(name: 'Студент')
    @students = student.users.paginate(page: params[:page], per_page: 10)
    add_breadcrumb 'Пользователи', :users_url
    add_breadcrumb 'Студенты', :students_url
  end

  def new
    @user = User.new
    add_breadcrumb 'Пользователи', :users_url
    add_breadcrumb 'Новый пользователь', :new_user_url
  end

  def create
    @user = User.new(user_params)
    add_roles(@user)

    if @user.save
      @user.send_reset_password_instructions
      flash[:success] = 'Пользователь успешно создан'
      redirect_to @user
    else
      flash[:danger] = 'Вы ввели некорректные данные, проверьте и попробуйте снова'
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
    add_breadcrumb 'Пользователи', :users_url
    add_breadcrumb 'Редактирование данных пользователя - ' + @user.full_name
  end

  def update
    @user = User.find(params[:id])
    if @user.has_role? 'Администратор'
      add_roles(@user)
    end

    if @user.update(user_params)
      redirect_to @user
      flash[:success] = 'Данные пользователя успешно обновлены'
    else
      flash[:danger] = 'Вы ввели некорректные данные, проверьте и попробуйте снова'
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])

    @user.destroy
    flash[:success] = 'Пользователь успешно удален'
    redirect_to users_url
  end

  private

  def user_params
    params.require(:user).permit(:name, :surname, :birthdate, :gender, :passport_data, :photo, :passport_scan_copy,
                                 :email, :password, group_ids: [], role_ids: [],
                                 contact_attributes: [:id, :phone, :additional_phone, :skype])
  end

  def add_roles(user)
    user.roles = []
    params[:user][:role_ids].each do |r|
      user.roles.push(Role.find(r)) unless r.blank?
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_contact_info.html.erb
<tr>
  <td class="col-sm-6">Номер телефона</td>
  <td class="col-sm-6"><%= @user.contact.phone %></td>
</tr>
<% unless @user.contact.additional_phone.empty? %>
  <tr>
    <td class="col-sm-6">Доп. номер телефона</td>
    <td class="col-sm-6"><%= @user.contact.additional_phone %></td>
  </tr>
<% end %>
<tr>
  <td class="col-sm-6">Skype</td>
  <td class="col-sm-6"><%= @user.contact.skype %></td>
</tr>
<tr>
  <td class="col-sm-6">Email</td>
  <td class="col-sm-6"><%= @user.email %></td>
</tr>

app/views/users/_form.html.erb
<%= render 'users/sidebar_users' %>

<% if current_user.has_role? 'Администратор' %>
  <%= form_for @user, html: {class: 'form-horizontal'} do |f| %>
    <div class="form-group">
      <%= f.label :name, 'Имя*', class: 'col-sm-3 control-label' %>
      <div class="col-sm-6">
        <%= f.text_field :name, autofocus: true, class: 'form-control' %>
        <%= render 'shared/field_errors', object: @user, field_name: :name %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :surname, 'Фамилия*', class: 'col-sm-3 control-label' %>
      <div class="col-sm-6">
        <%= f.text_field :surname, class: 'form-control' %>
        <%= render 'shared/field_errors', object: @user, field_name: :surname %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :birthdate, 'Дата рождения*', class: 'col-sm-3 control-label' %>
      <div class="col-sm-6">
        <%= f.date_select :birthdate, order: [:day, :month, :year], start_year: 1950,
                          prompt: { day: 'День', month: 'Месяц', year: 'Год' },
                          class: 'form-control' %>
        <%= render 'shared/field_errors', object: @user, field_name: :birthdate %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :gender, 'Пол*', class: 'col-sm-3 control-label' %>
      <div class="col-sm-6">
        <div class="radio-inline">
          <%= f.radio_button :gender, 'мужской', :checked => true %> Мужской
        </div>
        <div class="radio-inline">
          <%= f.radio_button :gender, 'женский' %> Женский
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :photo, 'Фотография', class: 'col-sm-3 control-label' %>
      <div class="col-sm-6">
        <%= f.file_field :photo %>
        <span class="help-block">Разрешенные форматы: jpeg, jpg, gif, png</span>
        <%= render 'shared/field_errors', object: @user, field_name: :photo %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :passport_data, 'Паспортные данные*', class: 'col-sm-3 control-label' %>
      <div class="col-sm-6">
        <%= f.text_field :passport_data, class: 'form-control' %>
        <%= render 'shared/field_errors', object: @user, field_name: :passport_data %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :passport_scan_copy, 'Скан-копия паспорта', class: 'col-sm-3 control-label' %>
      <div class="col-sm-6">
        <%= f.file_field :passport_scan_copy %>
        <span class="help-block">Разрешенные форматы: jpeg, jpg, gif, png</span>
        <%= render 'shared/field_errors', object: @user, field_name: :passport_scan_copy %>
      </div>
    </div>

    <%= f.fields_for(:contact) do |ff| %>
        <div class="form-group">
          <%= ff.label :phone, 'Номер телефона*', class: 'col-sm-3 control-label' %>
          <div class="col-sm-6">
            <%= ff.text_field :phone, class: 'form-control' %>
            <span class="help-block">996###xxxxxx, где ### - код моб. оператора/города, xxxxxx - номер телефона</span>
            <%= render 'shared/field_errors', object: @user.contact, field_name: :phone %>
          </div>
        </div>

        <div class="form-group">
          <%= ff.label :additional_phone, 'Доп. номер телефона', class: 'col-sm-3 control-label' %>
          <div class="col-sm-6">
            <%= ff.text_field :additional_phone, class: 'form-control' %>
            <span class="help-block">996###xxxxxx, где ### - код моб. оператора/города, xxxxxx - номер телефона</span>
            <%= render 'shared/field_errors', object: @user.contact, field_name: :additional_phone %>
          </div>
        </div>

        <div class="form-group">
          <%= ff.label :skype, 'Skype*', class: 'col-sm-3 control-label' %>
          <div class="col-sm-6">
            <%= ff.text_field :skype, class: 'form-control' %>
            <%= render 'shared/field_errors', object: @user.contact, field_name: :skype %>
          </div>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.label :email, 'Email*', class: 'col-sm-3 control-label' %>
      <div class="col-sm-6">
        <%= f.email_field :email, class: 'form-control' %>
        <span class="help-block">Только gmail</span>
        <%= render 'shared/field_errors', object: @user, field_name: :email %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :roles, 'Статус*', class: 'col-sm-3 control-label' %>
      <div class="col-sm-6">
        <div class="checkbox-inline">
          <%= f.collection_check_boxes(:role_ids, Role.all, :id, :name) do |r| %>
            <p class="normal"><%= r.label { r.check_box + ' ' + r.text } %></p>
          <% end %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-3 col-sm-6">
        <%= f.submit 'Сохранить', class: 'btn btn-default' %>
      </div>
    </div>
  <% end %>

<% else %>

  <%= form_for @user, html: {class: 'form-horizontal'} do |f| %>
    <div class="form-group">
      <%= f.label :photo, 'Фотография', class: 'col-sm-3 control-label' %>
      <div class="col-sm-6">
        <%= f.file_field :photo %>
        <span class="help-block">Разрешенные форматы: jpeg, jpg, gif, png</span>
        <%= render 'shared/field_errors', object: @user, field_name: :photo %>
      </div>
    </div>

    <%= f.fields_for(:contact) do |ff| %>
      <div class="form-group">
        <%= ff.label :phone, 'Номер телефона*', class: 'col-sm-3 control-label' %>
        <div class="col-sm-6">
          <%= ff.text_field :phone, class: 'form-control' %>
          <span class="help-block">996###xxxxxx, где ### - код моб. оператора/города, xxxxxx - номер телефона</span>
          <%= render 'shared/field_errors', object: @user.contact, field_name: :phone %>
        </div>
      </div>

      <div class="form-group">
        <%= ff.label :additional_phone, 'Доп. номер телефона', class: 'col-sm-3 control-label' %>
        <div class="col-sm-6">
          <%= ff.text_field :additional_phone, class: 'form-control' %>
          <span class="help-block">996###xxxxxx, где ### - код моб. оператора/города, xxxxxx - номер телефона</span>
          <%= render 'shared/field_errors', object: @user.contact, field_name: :additional_phone %>
        </div>
      </div>

      <div class="form-group">
        <%= ff.label :skype, 'Skype*', class: 'col-sm-3 control-label' %>
        <div class="col-sm-6">
          <%= ff.text_field :skype, class: 'form-control' %>
          <%= render 'shared/field_errors', object: @user.contact, field_name: :skype %>
        </div>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :email, 'Email*', class: 'col-sm-3 control-label' %>
      <div class="col-sm-6">
        <%= f.email_field :email, class: 'form-control' %>
        <span class="help-block">Только gmail</span>
        <%= render 'shared/field_errors', object: @user, field_name: :email %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :password, 'Пароль', class: 'col-sm-3 control-label' %>
      <div class="col-sm-6">
        <%= f.password_field :password, autocomplete: 'off', class: 'form-control' %>
        <span class="help-block">(оставьте поле пустым, если не хотите менять пароль)</span>
        <%= render 'shared/field_errors', object: @user, field_name: :password %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :password_confirmation, 'Подтверждение пароля', class: 'col-sm-3 control-label' %>
      <div class="col-sm-6">
        <%= f.password_field :password_confirmation, autocomplete: 'off', class: 'form-control' %>
        <%= render 'shared/field_errors', object: @user, field_name: :password_confirmation %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :current_password, 'Текущий пароль', class: 'col-sm-3 control-label' %>
      <div class="col-sm-6">
        <%= f.password_field :current_password, autocomplete: "off", class: 'form-control' %>
        <%= render 'shared/field_errors', object: @user, field_name: :current_password %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-3 col-sm-6">
        <%= f.submit 'Сохранить', class: 'btn btn-default' %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/users/_general_info.html.erb
<%= render 'users/sidebar_users' %>

<tr>
  <td class="col-sm-6">Имя</td>
  <td class="col-sm-6"><%= @user.name %></td>
</tr>
<tr>
  <td class="col-sm-6">Фамилия</td>
  <td class="col-sm-6"><%= @user.surname %></td>
</tr>
<tr>
  <td class="col-sm-6">Дата рождения</td>
  <td class="col-sm-6"><%= @user.birthdate %></td>
</tr>
<tr>
  <td class="col-sm-6">Пол</td>
  <td class="col-sm-6"><%= @user.gender %></td>
</tr>
<tr>
  <td class="col-sm-6">Паспортные данные</td>
  <td class="col-sm-6"><%= @user.passport_data %></td>
</tr>
<tr>
  <td class="col-sm-6">Скан-копия паспорта</td>
  <% if @user.passport_scan_copy.exists? %>
    <td class="col-sm-6"><%= link_to @user.passport_scan_copy_file_name, @user.passport_scan_copy.url(:large) %></td>
  <% else %>
    <td>Файл не загружен</td>
  <% end %>
</tr>

app/views/users/_sidebar_users.html.erb
<ul class="nav navbar-nav side-nav">
	<div class="my-avatar">
		<%= link_to image_tag(current_user.photo.url(:thumb), class: 'img-circle'), authenticated_root_path %>
	</div>

	<ul class="nav nav-stacked">
		<li><%= link_to '<i class="fa fa-users fa-lg"></i> Пользователи'.html_safe, users_path %></li>
		<li><%= link_to '<i class="fa fa-briefcase fa-lg"></i> Курсы' .html_safe, courses_path %></li>
		<li><%= link_to '<i class="fa fa-circle fa-lg"></i> Группы'.html_safe, groups_path %></li>
	</ul>
</ul>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/index.html.erb
<%= render 'users/sidebar_users' %>
<p><%= link_to 'Добавить пользователя', new_user_path, class: 'btn btn-default margin-bottom' %></p>
<%= link_to '<i class="fa fa-graduation-cap fa-lg"></i>'' Студенты'.html_safe,  students_path, class:'btn btn-default margin-bottom' %>



<table class="table table-striped table-hover col-sm-12">
  <tr>
    <th>Пользователь</th>
    <th>Статус</th>
    <th>Действия</th>
  </tr>

  <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.full_name, user_path(user) %></td>
        <td>
          <%= user.roles.map { |role| role.name }.join(', ') %>
        </td>
        <td>
          <%= link_to '<i class="fa fa-pencil-square-o fa-lg"></i>'.html_safe, edit_user_path(user), class: 'btn btn-default btn-xs' %>
          <%= link_to '<i class="fa fa-remove fa-lg"></i>'.html_safe, user_path(user), method: :delete,
                      data: {confirm: 'Вы действительно хотите удалить данного пользователя?'}, class: 'btn btn-danger btn-xs' %>
        </td>
      </tr>
  <% end %>
</table>
<div class="row">
  <div class="col-sm-12">
    <%= will_paginate @users %>
  </div>
</div>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/profile.html.erb
<%= render 'users/sidebar_users' %>
<div class="my-profile-info">
  <div class="col-sm-6">
    <div class="panel panel-default">
      <div class="panel-body">
        <h4>Общая информация</h4><hr/>
        <table class="table">
          <%= render 'general_info' %>
          <tr>
            <td class="col-sm-6">Cтатус</td>
            <td class="col-sm-6"><%= @user.roles.map { |role| role.name }.join(', ') %></td>
          </tr>
        </table>
      </div>
    </div>
  </div>

  <div class="col-sm-6">
    <div class="panel panel-default">
      <div class="panel-body">
        <h4>Контактные данные</h4><hr/>
        <table class="table">
          <%= render 'contact_info' %>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= render 'users/sidebar_users' %>

<div class="user-info">
  <div class="col-sm-12">
    <div class="panel">
      <div class="panel-heading">
        <h3 class="panel-title">
          <span>
            <%= @user.full_name %> - <%= @user.roles.map { |role| role.name }.join(', ') %>
          </span>
          <%= link_to '<i class="fa fa-file-text-o fa-lg"></i>'.html_safe, '#', class: 'btn btn-default btn-xs' %>
          <%= link_to '<i class="fa fa-pencil-square-o fa-lg"></i>'.html_safe, edit_user_path(@user), class: 'btn btn-default btn-xs' %>
          <%= link_to '<i class="fa fa-remove fa-lg"></i>'.html_safe, user_path(@user), method: :delete,
                      data: {confirm: 'Вы действительно хотите удалить данного пользователя?'}, class: 'btn btn-danger btn-xs' %>
        </h3>
      </div>
      <div class="panel-body">
        <div class="col-sm-5">
          <div class="user-photo">
            <%= image_tag @user.photo.url(:medium), class: 'img-thumbnail' %>
          </div>
        </div>
        <div class="col-sm-7">
          <h4>Общая информация</h4>
          <table class="table">
            <%= render 'general_info' %>
          </table>
          <h4>Контактные данные</h4>
          <table class="table">
            <%= render 'contact_info' %>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/students.html.erb
<%= render 'users/sidebar_users' %>

<!--<p><%= link_to 'Добавить студента', new_user_path, class: 'btn btn-default margin-bottom' %></p>-->

<table class="table table-striped table-hover col-sm-12">
  <tr>
    <th>Студент</th>
    <th>Действия</th>
  </tr>

  <% @students.each do |student| %>
      <tr>
        <td><%= link_to student.full_name, user_path(student) %></td>
        <td>
          <%= link_to '<i class="fa fa-pencil-square-o fa-lg"></i>'.html_safe, edit_user_path(student), class: 'btn btn-default btn-xs' %>
          <%= link_to '<i class="fa fa-remove fa-lg"></i>'.html_safe, user_path(student), method: :delete,
                      data: {confirm: 'Вы действительно хотите удалить данного студента?'}, class: 'btn btn-danger btn-xs' %>
        </td>
      </tr>
  <% end %>
</table>
<div class="row">
  <div class="col-sm-12">
    <%= will_paginate @students %>
  </div>
</div>